name: musicus_client
description: Client library for the Musicus server.
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  http:
  meta:
  moor:

dev_dependencies:
  build_runner:
  moor_generator: