name: musicus_client
description: Client library for the Musicus server.
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  drift: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.10
  drift_dev: ^1.0.0
