name: musicus
version: 0.1.0
description: The classical music player and organizer.
author: Elias Projahn <johrpan@gmail.com>
homepage: https://musicus.org
repository: https://github.com/johrpan/musicus

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  audio_service:
  flutter:
    sdk: flutter
  musicus_common:
    path: ../common
  musicus_player:
    path: ../player
  path:
  path_provider:
  shared_preferences:

flutter:
  uses-material-design: true
