name: musicus_server
description: A server hosting a Musicus database.
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  aqueduct:
  corsac_jwt:
  moor: ^3.0.2
  moor_ffi: ^0.5.0
  musicus_database:
    path: ../database
  steel_crypt:

dev_dependencies:
  build_runner:
  moor_generator: ^3.0.0
