name: musicus_database
description: A database for classical music.
version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  moor:
  moor_ffi:

dev_dependencies:
  build_runner:
  moor_generator: