name: musicus_common
version: 0.1.0
description: Common building blocks for Musicus client apps.

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  drift: ^1.0.0
  flutter:
    sdk: flutter
  flutter_markdown:
  meta:
  musicus_database:
    path: ../database
  path: ^1.8.1
  rxdart:
  url_launcher: ^6.1.0

flutter:
  uses-material-design: true
  assets:
  - assets/about.md
  fonts:
  - family: Libertinus Sans
    fonts:
    - asset: fonts/libertinussans_regular.otf
    - asset: fonts/libertinussans_bold.otf
      weight: 700
    - asset: fonts/libertinussans_italic.otf
      style: italic
  - family: Musicus Icons
    fonts:
    - asset: fonts/musicus_icons.ttf
