name: musicus_desktop
version: 0.1.0
description: Desktop version of the classical music player and organizer.

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: bd722fbdb6d491d4b7781c240543ed3b3b181063
  flutter:
    sdk: flutter
  musicus_common:
    path: ../common
  path:
  path_provider:
  shared_preferences:

flutter:
  uses-material-design: true
