name: musicus_desktop
version: 0.1.0
description: Desktop version of the classical music player and organizer.
publish_to: none

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  musicus_common:
    path: ../common
  musicus_database:
    path: ../database
  path:
  path_provider:
  shared_preferences:

flutter:
  uses-material-design: true
